#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_


#define H_RES 800
#define V_RES 600
#define HEADER_HEIGHT 20
#define FOOTER_HEIGHT 20
#define ARENA_WIDTH 800
#define ARENA_HEIGHT 560
#define VIRUS1_WIDTH 40
#define VIRUS1_HEIGHT 40
#define VIRUS2_WIDTH 50
#define VIRUS2_HEIGHT 50
#define SPAWN_OFFSET 100
#define LETTERS_NUM 26
#define NUMBERS_NUM 10
#define MENU_FONT_OFFSET 4
#define MENU_FONT_HEIGHT 26
#define MENU_FONT_WIDTH 25
#define GAME_FONT_OFFSET 3
#define GAME_FONT_HEIGHT 18
#define GAME_FONT_WIDTH 18
#define TITLE_FONT_OFFSET 6
#define TITLE_FONT_WIDTH 39
#define TITLE_FONT_HEIGHT 39

#define HYSTERESIS_THRESHOLD 30.0


#endif // _CONSTANTS_H_

